### ISSUE TITLE
How to specify a hook (e.g. postInstall) only for the main package?

### ISSUE THREAD

**Issue by cole-h** [nmattia/naersk#105]
I was wondering if it's possible (or could be made possible) to keep extraneous top-level directories. For example, my project has a `completions` folder that I would like available, so I can add `installShellCompletion` to my `postInstall`. Currently, I do `installShellCompletion --fish ${./completions/passrs.fish}`, but it would be nice if I could instead just do `installShellCompletion --fish $src/completions/passrs.fish`.

**Comment by cole-h** [comment]
So, I did a little bit of testing...

My problem comes from the fact that `postInstall` is ran for both the dependencies and the actual binary build itself. For now, I've worked around this by doing `installShellCompletion --fish ./completions/passrs.fish || true` so the build won't fail when the dependencies don't have a completions folder.

If there was some way to specify e.g. a `postInstallPackage` (`postFixupPackage`, etc.) to be run only when building the main package and not dependencies, I would be satisfied.

**Comment by nmattia** [comment]
Hi @cole-h , sorry for the delay. I was out for a while a it literally took me months to catch up with notifications. Do you have some code you can share? You can always call `overrideAttrs` on the derivation, that'll only impact the main package!

**Comment by cole-h** [comment]
I totally understand, no worries!

The code I currently have is here: https://github.com/cole-h/passrs/blob/860f43dcfe064ab9e7990712b5e932a5a2e57fc2/flake.nix#L41-L74. While `overrideAttrs` does work, it would be nice if there were hooks that only fired when building the main package and not the `deps`.

**Comment by nmattia** [comment]
True, I think something like this would be nice:


``` nix
        buildPackage {
          pname = "passrs";

          ...

          override = { ... }; # just like we have now, applied to all crates

          # only applied to the top-level derivation; may also be a function
          overrideMain = {
            postInstall = ''
              installShellCompletion --fish completions/passrs.fish || true
            '';
          };
        }
```

**Comment by cole-h** [comment]
I like that :+1:
