### ISSUE TITLE
`postInstall` and probably other hooks called for main and deps

### ISSUE THREAD

**Issue by NobbZ** [nmattia/naersk#121]
When one uses hooks in `buildPackage` with an attribute set, then those hooks are called for the deps as well as the main derivation, this has some downsides:

1. Hooks might fail with confusing error messages, as one expects them to be run for the main derivation only, and one wonders why there is no `$out/bin` in the `postInstall`, but `./result/bin` exists when one removes that hook.
2. Additional logic is necessary to decide whether or not we are in the main or deps derivation. In my particular case I can check for existence of a folder in `$out` as I'm doing a `postInstall`, though those conditions might become arbitrary complex if deps and main had overlapping content.
3. If I tweak the phases/hooks to run additional commands on files (eg. generating code files or patching sources) I have to rebuild the deps derivation despite their output won't change.

To mitigate all of this, I'd propose to not pass those attributes to the deps derivations or introduce special attributes for hooks/phases related to the deps derivation (perhaps a nested set in `depsPhases` which then accepts the regular `phases` list as well as the various `xPhases`, `preX`, and `postX` attributes).

**Comment by nmattia** [comment]
Hi,

Would the `override` and `overrideMain` attribute from the [configuration](https://github.com/nmattia/naersk/tree/d645515b7159c75087b3d51f23a68047c2c09699#configuration) work for you? You can call them like this:

``` nix
buildPackage 
  { src = ./foo;
    override = { postBuild = "run me after any derivation was built"; };
    overrideMain = { postInstall = "run me after the main derivation has finished the install phase"; };
  }
```

**Comment by NobbZ** [comment]
This indeed seems to work.

When I read the README, I thought those are like `override` in a derivation and can only replace original function call arguments.

Though they seem to work more like the `overrideAttrs` "method", therefore I have also to say, correct syntax for your snippet would be this:

```nix
buildPackage 
  { src = ./foo;
    override = _: { postBuild = "run me after any derivation was built"; };
    overrideMain = _: { postInstall = "run me after the main derivation has finished the install phase"; };
  }
```
