### ISSUE TITLE
Flakes: How to build/run packages/apps other than the defaults?

### ISSUE THREAD

**Issue by paulyoung** [nmattia/naersk#177]
`nix build` and `nix run` work fine since `defaultPackage = packages.my-project;` and `defaultApp = apps.my-project` are set.

However, `nix build my-project` and `nix run my-project` (and the `.#my-project` variants) result in:

```
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------- nix
cannot find flake 'flake:my-project' in the flake registries
```

I'm using a Cargo workspace and trying to build packages/apps that aren't the defaults.

**Comment by leo60228** [comment]
I think this question might be more suited for https://discourse.nixos.org. 
As to the question itself, `nix run my-project` is different to `nix run .#my-project`, and you want the latter. I wouldn't expect them to give the same error.

**Comment by paulyoung** [comment]
Asked here: https://discourse.nixos.org/t/flakes-how-to-build-run-packages-apps-other-than-the-defaults/13183
