### ISSUE TITLE
Updating git repository during build throws "failed to resolve address" error

### ISSUE THREAD

**Issue by Witcher01** [nmattia/naersk#279]
Building with Nix throws me a "failed to resolve address":

```
    Updating git repository `https://git.sr.ht/~witcher/unlisted-repo`
warning: spurious network error (2 tries remaining): failed to resolve address for git.sr.ht: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for git.sr.ht: Temporary failure in name resolution; class=Net (12)
error: failed to load source for dependency `unlisted-repo`
```

My Cargo.toml has a patched dependency:

```toml
[patch.crates-io]
unlisted_repo = { git = "https://git.sr.ht/~witcher/unlisted-repo" }
```

Building with `cargo` works just fine, the repo is accessible and the address resolves. No authentication is needed to access the repository.

**Comment by Patryk27** [comment]
Hmm, interesting!

If you're using Nix Flakes, are you sure you've got `Cargo.lock` committed into the repository as well, so that Naersk can see it?

**Comment by Patryk27** [comment]
Possibly; I'm using Naersk with "external" patched dependencies myself (to a private GitLab instance) and everything works fine, so maybe it was just a temporary network issue 👀
