### ISSUE TITLE
Interface of buildPackage

### ISSUE THREAD

**Issue by nmattia** [nmattia/naersk#32]
Right now `buildPackage` takes two arguments: a path and an attribute set. The reasoning is that in most cases it'll look like this:

``` nix
naersk.buildPackage ./path/to/src {}
```

There are two problems:

1. causes confusion
1. in most cases we're passing an empty attribute set

So instead I suggest we have a single argument which is either a path or an attribute set with mandatory field `src`.

@basvandijk @zimbatm @Profpatsch you guys might be using it, thoughts? I'd rather break everything before naersk is officially released.

**Comment by zimbatm** [comment]
I think I suggested this interface already. There is also a precedence in the nix world, for example `builtins.fetchGit` also either takes a path or an attrset.

**Comment by nmattia** [comment]
Sold!

**Comment by Profpatsch** [comment]
Me likey.
