### ISSUE TITLE
Git dependency: failed to clone

### ISSUE THREAD

**Issue by curiousleo** [nmattia/naersk#39]
I have a dependency in my `Cargo.toml` that is specified via a Git repo and `rev`: https://github.com/curiousleo/keygen/blob/niv/Cargo.toml#L12-L14

This fails to build with the following error:

```console
$ nix-build .
warning: dumping very large path (> 256 MiB); this may run out of memory
these derivations will be built:
  /nix/store/99n7i74rgpd4r5az8j8jhc53l7r4ssnd-keygen-deps-0.1.0.drv
  /nix/store/gl8p2sf311kzpy93r76lfmf6575495pk-keygen-0.1.0.drv
building '/nix/store/99n7i74rgpd4r5az8j8jhc53l7r4ssnd-keygen-deps-0.1.0.drv'...
unpacking sources
unpacking source archive /nix/store/r9bnlqy5709ch7c5kxml9bnpwqpz0hpl-dummy-src
source root is dummy-src
patching sources
configuring
building
cargo build --release -j 8 -Z unstable-options --out-dir out
    Updating git repository `https://gitlab.com/sequoia-pgp/sequoia.git`
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name; class=Net (12)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name; class=Net (12)
error: failed to load source for a dependency on `sequoia-openpgp`

Caused by:
  Unable to update https://gitlab.com/sequoia-pgp/sequoia.git?rev=7735b05e8cf82ae943e8b7b0dfed4a26cd6c3db4#7735b05e

Caused by:
  failed to clone into: /build/dummy-src/.cargo-home/git/db/sequoia-67f184fe09141952

Caused by:
  [6] Couldn't resolve host name; class=Net (12)
builder for '/nix/store/99n7i74rgpd4r5az8j8jhc53l7r4ssnd-keygen-deps-0.1.0.drv' failed with exit code 101
cannot build derivation '/nix/store/gl8p2sf311kzpy93r76lfmf6575495pk-keygen-0.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/gl8p2sf311kzpy93r76lfmf6575495pk-keygen-0.1.0.drv' failed
```

(`cargo build` succeeds, so that revision is definitely there and can be downloaded.)

Repro case: [this branch](https://github.com/curiousleo/keygen/tree/niv):

```console
$ pushd $(mktemp -d)
$ curl -L https://api.github.com/repos/curiousleo/keygen/tarball/niv | tar xz --strip=1
$ nix-build .
```

**Comment by nmattia** [comment]
Hi @curiousleo ,

`naersk` is not officially "released" yet, though I should probably write a list of features in the README.

This is an unfortunate limitation of naersk. Since the `Cargo.lock` does not register checksums for git dependencies, naersk is unable to pre-fetch them. More information on [cargo#7059](https://github.com/rust-lang/cargo/issues/7059).

I know @Profpatsch was looking into this. Here's what I suggested doing:

> @Profpatsch if you want to support git deps I think you'll need to add a source patch here: https://github.com/nmattia/naersk/blob/f17317465e43ad7b9945e6492295e190946fb4ac/build.nix#L72 that'll point to your nix-fetched git source.
> actually you should be able to iterate over your sources and builtins.fetchgit them (though you still need to patch in the cargo config)

## unrelated

> warning: dumping very large path (> 256 MiB); this may run out of memory

you're probably pulling your `target` directory into your nix store. You should call `lib.cleanSource ./.` instead of `./.` if you want to avoid this:

https://github.com/curiousleo/keygen/blob/61751442e821120db0b0e0ccd53d5804d0a9984f/default.nix

As of today this is handled automatically by naersk: https://github.com/nmattia/naersk/pull/38

**Comment by curiousleo** [comment]
> `naersk` is not officially "released" yet, though I should probably write a list of features in the README.

Thanks, I think such a list would be useful to set expectations appropriately.

> This is an unfortunate limitation of naersk. Since the `Cargo.lock` does not register checksums for git dependencies, naersk is unable to pre-fetch them. More information on [cargo#7059](https://github.com/rust-lang/cargo/issues/7059).

> I know @Profpatsch was looking into this.

I may have a chat with him then, perhaps he has had time to look into this. Thanks for the pointer!

> you're probably pulling your `target` directory into your nix store. You should call `lib.cleanSource ./.` instead of `./.` if you want to avoid this:
> 
> https://github.com/curiousleo/keygen/blob/61751442e821120db0b0e0ccd53d5804d0a9984f/default.nix
> 
> As of today this is handled automatically by naersk: #38

Cheers! Yeah I threw this together quickly as a test. Appreciate the pointer to `lib.cleanSource`.

**Comment by nmattia** [comment]
Actually I realized this is already mentioned in the README:

> Because cargo doesn't register checksums for git dependencies, naersk does not support git dependencies.

I've made this more visible: https://github.com/nmattia/naersk/pull/40

**Comment by bqv** [comment]
So about this, with #48 sorted we'll already have the full git revision of a git dependency, I don't see a good reason why that can't be used in substitute for a checksum, since it is still a hash of the content.
