### ISSUE TITLE
Cannot detect Cargo.toml's [workspace] with nested members declaration

### ISSUE THREAD

**Issue by Rizary** [nmattia/naersk#53]
Hi, I am using niv to add https://github.com/rust-analyzer/rust-analyzer/ into my project.

Then, I have the following code:
```
rust-analyzer-src = (import ./nix/sources.nix).rust-analyzer;
rust-analyzer = pkgs.naerks.buildPackage rust-analyzer-src;
```
into my `shell.nix`. However, when I try to run `nix-shell` I got the following error:

```opening file ' nix/store/r193....-source/crates/*/Cargo.toml': No such file or directory``` while the `crates` folder exists in the `rust-analyzer` package.

**Comment by Rizary** [comment]
For more information, here is the screenshot of the error:

![image](https://user-images.githubusercontent.com/7221768/72196060-40f04800-3448-11ea-825d-7fd249ea72be.png)

**Comment by Rizary** [comment]
Digging further, I think the problem lies in this code:

https://github.com/nmattia/naersk/blob/master/config.nix#L173-L178 of

```
    cargotomls =
      let
        readTOML = builtinz.readTOML usePureFromTOML;
      in
        { "." = toplevelCargotoml; } // lib.optionalAttrs isWorkspace
          (
            lib.listToAttrs
              (
                map
                  (
                    member:
                      {
                        name = member;
                        value = readTOML (root + "/${member}/Cargo.toml");
                      }
                  )
```

And in the rust-analyzer's Cargo.toml, the workspace contain `"crates/*"` value:
```
  
[workspace]
members = [ "crates/*", "xtask/" ]
```

Which reads literally `"crates/*"` by this `readTOML (root + "/${member}/Cargo.toml");`

**Comment by Rizary** [comment]
### [Update]

I try to create some workaround like the following:

![image](https://user-images.githubusercontent.com/7221768/72199860-c4279300-3474-11ea-8e64-9069cd56d0bd.png)


But then I got the Error:

`Error: evaluation aborted with the following error message: 'Not implemented: type int'`

And I have no idea where to look at it in the code/rust-analyzer.

**Comment by nmattia** [comment]
> the workspace contain "crates/*" value:

I had no idea that was possible! I'll fix this on Monday.

Re the `Not implemented: type int` that seems to come from the [toTOML](https://github.com/nmattia/naersk/blob/be6d7bfe6132d7b0bf93fa754f35fb6be516b25f/builtins/to-toml.nix) function. Is it possible your cargo tomls contain integers? You should be able to work around that by setting `buildPackage { src = rust-analyzer-src; singleStep = true }` although that might be a bit slow.

**Comment by Rizary** [comment]
Thank you! Can't wait to see the new fix.

I am not familiar with cargo an toml yet (still new to rust). Do I have to check all `Cargo.toml`  in the project and its dependencies?

If yes, in the root project, it contains integers (see below):

```
[workspace]
members = [ "crates/*", "xtask/" ]

[profile.dev]
# disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.release]
incremental = true
debug = 0 # set this to 1 or 2 to get more useful backtraces in debugger

[patch.'crates-io']
# rowan = { path = "../rowan" }
```
