### ISSUE TITLE
Compiled binaries depend on the crate source code

### ISSUE THREAD

**Issue by Xe** [nmattia/naersk#71]
When I build my [rust project](https://github.com/Xe/withinbot) as a Docker image, I get a ~200 MB image. This seems to be because every single one of the crates it depends on gets included into the resulting binary. Here is how I am building a docker image:

- https://github.com/Xe/withinbot/blob/master/docker.nix
- https://github.com/Xe/withinbot/blob/master/default.nix

How do I remove references to the crates from the compiled binary? The paths to the crates seem to live in the Rust panicinfo crud.

**Comment by andrew-d** [comment]
`rustc` has a `--remap-path-prefix FROM=TO` option that, per the manpage:

> Remap source names in all output (compiler messages and output files)

It should be possible to pass this via the `RUSTFLAGS` environment variable; see the [`cargo` test suite](https://github.com/rust-lang/cargo/blob/79d845b42b64747e0c270e629b9064556fab45e2/tests/testsuite/rustflags.rs#L1367-L1399) for an example.

**Comment by Xe** [comment]
Thanks much all! This helps a lot.
