### ISSUE TITLE
Use builtins.fetchGit

### ISSUE THREAD

**Issue by leo60228** [nmattia/naersk#72]
While `cargo.lock` doesn't include a checksum of Git repositories, it does include the commit hash. `builtins.fetchGit` wasn't used initially due to having a one-hour timeout... but this only happens if you don't specify a commit hash. https://github.com/NixOS/nix/blob/f800d450b78091835ab7ca67847d76e75d877a24/src/libexpr/primops/fetchGit.cc#L103-L123

**Comment by leo60228** [comment]
And... this is already supported. This is what happens when you look at outdated docs...

**Comment by nmattia** [comment]
@leo60228 you mean outdated docs for naersk? can you point out which? Thanks!
