### ISSUE TITLE
Binary not on PATH in nix-shell

### ISSUE THREAD

**Issue by energizah** [nmattia/naersk#80]
Hello, I tried installing a package with Naersk. 

I'm not sure whether I'm doing something wrong or there's an issue.

I expected `grex` to be on PATH but it isn't. I made a repo to help reproduce what I'm seeing: 

```
git clone https://github.com/energizah/naersk-demo.git
cd naersk-demo
nix-shell
grex --help
```
Gives `grex: Command not found`

On the other hand, 

```
git clone https://github.com/pemistahl/grex
cd grex
cargo build
cargo run grex --help
```
works fine.

**Comment by basvandijk** [comment]
I believe this makes all the dependencies of `grex` available in the shell. If you need access to `grex` itself consider using [`mkShell`](https://nixos.org/nixpkgs/manual/#sec-pkgs-mkShell).

**Comment by energizah** [comment]
My mistake, that does the trick. Thank you.
